config/routes.rb
Rails.application.routes.draw do
  root "events#index"
  get "/events/selectEvent" => "events#selectEvent" # if this line is after resources events, it will think selectEvent is an id
  get "/events/qrCode/:id" => "events#qrCode", as: "event_qrCode"
  get "/rewards/testEmail" => "rewards#testEmail"
  get "/rewards/:id/editRedemption" => "rewards#editRedemption", as: "edit_redemption"
  resources :users
  resources :announcements
  resources :rewards
  resources :events
  resources :redemptions
 
  get "/cheese" => "events#getAllEvents"
  get "/userFromToken" => "users#user_info"
  get "/userRewards" => "users#getRewards"
  patch "/usersMobile/:netid" => "users#updateFromMobile"
  patch "/usersMobile" => "users#updateFromMobile"
  patch "/redeem/:id" => "rewards#redeemReward"
  get "/users/showImage/:id" => "users#showImage", as: :user_showImage
  post "/attend/:id" => "users#eventScan"
  get "/confirmReward/:qrcode" => "rewards#confirmReward"
  get "/uniqueUsername" => "users#uniqueUsername"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  # Render Web App Interface

  # get "/events" => "events#index"
  # get "/rewards" => "rewards#index"
  # get "/announcements" => "announcements#index"
  # get "/users" => "users#index"

end

app/models/announcement.rb
class Announcement < ApplicationRecord
    validates :title, presence: true
    validates :description, presence: true
    validates :category, presence: true
end

app/controllers/announcements_controller.rb
class AnnouncementsController < ApplicationController
  before_action :set_announcement, only: [:show, :edit, :update, :destroy]

  # GET /announcements
  # GET /announcements.json
  def index
    # @announcements = Announcement.all
    @announcements = Announcement.order('created_at DESC')
    respond_to do |format|
      format.html 
      format.json { render json: {status: 'SUCCESS', message: 'Loaded rewards', data:@announcements}, status: :ok}
    end
  end

  # GET /announcements/1
  # GET /announcements/1.json
  def show
  end

  # GET /announcements/new
  def new
    @announcement = Announcement.new
  end

  # GET /announcements/1/edit
  def edit
  end

  # POST /announcements
  # POST /announcements.json
  def create
    @announcement = Announcement.new(announcement_params)

    respond_to do |format|
      if @announcement.save
        format.html { redirect_to @announcement, notice: 'Announcement was successfully created.' }
        format.json { render :show, status: :created, location: @announcement }
      else
        format.html { render :new }
        format.json { render json: @announcement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /announcements/1
  # PATCH/PUT /announcements/1.json
  def update
    respond_to do |format|
      if @announcement.update(announcement_params)
        format.html { redirect_to @announcement, notice: 'Announcement was successfully updated.' }
        format.json { render :show, status: :ok, location: @announcement }
      else
        format.html { render :edit }
        format.json { render json: @announcement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /announcements/1
  # DELETE /announcements/1.json
  def destroy
    @announcement.destroy
    respond_to do |format|
      format.html { redirect_to announcements_url, notice: 'Announcement was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_announcement
      @announcement = Announcement.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def announcement_params
      params.require(:announcement).permit(:title, :description, :category)
    end
end

app/helpers/announcements_helper.rb
module AnnouncementsHelper
end

app/views/announcements/_form.html.erb
<%= form_with(model: announcement, local: true) do |form| %>
  <% if announcement.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(announcement.errors.count, "error") %> prohibited this announcement from being saved:</h2>

      <ul>
        <% announcement.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title, "Title:" %>
    <%= form.text_field :title, class: "short-text validationFixedWidth" %>
  </div>

  <div class="field">
    <%= form.label :description, "Description:" %>
    <%= form.text_area :description, class: "validationFixedWidthDescription" %>
  </div>

  <div class="field">
    <%= form.label :category, "Category:" %>
    <%= form.select :category, ["Athletics","Dining"], {:prompt => "Select Category"}, class: "validationFixedWidthCategory" %>
  </div>

  <div class="actions">
    <%= form.submit "Submit Announcement", class: "submit" %>
  </div>
<% end %>

app/views/announcements/edit.html.erb
<!DOCTYPE html>
<head>
    <meta charset='utf-8'/>
    <title>Duke Rewards</title>
    <%= stylesheet_link_tag "application.css" %>
    <link href="https://fonts.googleapis.com/css?family=Merriweather:400,400i,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300;0,400;0,700;1,400&display=swap" rel="stylesheet">
</head>

<body>
    <nav>
        <ul id="menu">
            <%= image_tag("duke_wordmark_white.png", :alt => "Duke Wordmark") %>
            <li class="name"> Duke Rewards </li>
            <li><%= link_to "REWARDS", rewards_path %></li>
            <li><%= link_to "EVENTS", events_path %></li>
            <li><%= link_to "ANNOUNCEMENTS", announcements_path, class: "active" %></li>

            <!-- <li><%= link_to "USERS", users_path %></li> -->
        </ul>
    </nav>
    
    <h1>Editing Announcement</h1>

    <ul id="toolbar">
        <li><%= link_to '+ Add', new_announcement_path %></li>
        <li><%= link_to 'Edit', announcements_path, class: "active" %></li>
    </ul>
    
    <div class="edit">
        <%= link_to 'Return to All Announcements', announcements_path, class: "back" %>
        <%= link_to 'Show', @announcement, class: "back" %>
        <%= render 'form', announcement: @announcement %>
    </div>
</body>

app/views/announcements/index.html.erb
<!DOCTYPE html>
<head>
    <meta charset='utf-8'/>
    <title>Duke Rewards</title>
    <%= stylesheet_link_tag "application.css" %>
    <link href="https://fonts.googleapis.com/css?family=Merriweather:400,400i,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300;0,400;0,700;1,400&display=swap" rel="stylesheet">
</head>

<body>
  <p id="notice"><%= notice %></p>

  <nav>
    <ul id="menu">
      <%= image_tag("duke_wordmark_white.png", :alt => "Duke Wordmark") %>
      <li class="name"> Duke Rewards </li>
      <li><%= link_to "REWARDS", rewards_path %></li>
      <li><%= link_to "EVENTS", events_path%></li>
      <li><%= link_to "ANNOUNCEMENTS", announcements_path, class: "active" %></li>

      <!-- <li><%= link_to "USERS", users_path %></li> -->
    </ul>
  </nav>

  <h1>Announcements</h1>

  <h2> Any announcement that gets created will notify every person with the Duke Rewards App through push notifications on their phone with the announcement message. All fields are required when creating an announcement. </h2>

  <ul id="toolbar">
      <li><%= link_to '+ Add', new_announcement_path %></li>
      <li><%= link_to 'Edit', announcements_path, class: "active" %></li>
  </ul>

  <div>
    <table>
      <thead>
        <tr>
          <th>Title</th>
          <th>Date Created</th>
          <th>Description</th>
          <th>Category</th>
          <th>Action</th>
        </tr>
      </thead>

      <tbody>
        <% @announcements.each do |announcement| %>
          <tr>
            <td><%= announcement.title %></td>
            <td><%= announcement.created_at.in_time_zone(ActiveSupport::TimeZone.new("Eastern Time (US & Canada)")).strftime("%F %H:%M %Z") %></td>
            <td><%= announcement.description %></td>
            <td><%= announcement.category %></td>
            <td class="no-wrap">
              <button><%= link_to 'Details', announcement %></button><br>
              <button><%= link_to 'Edit', edit_announcement_path(announcement) %></button><br>
              <button><%= link_to 'Remove', announcement, method: :delete, data: { confirm: 'Are you sure?' } %></button>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</body>

app/views/announcements/new.html.erb
<!DOCTYPE html>
<head>
    <meta charset='utf-8'/>
    <title>Duke Rewards</title>
    <%= stylesheet_link_tag "application.css" %>
    <link href="https://fonts.googleapis.com/css?family=Merriweather:400,400i,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300;0,400;0,700;1,400&display=swap" rel="stylesheet">
</head>

<body>
    <nav>
        <ul id="menu">
            <%= image_tag("duke_wordmark_white.png", :alt => "Duke Wordmark") %>
            <li class="name"> Duke Rewards </li>
            <li><%= link_to "REWARDS", rewards_path %></li>
            <li><%= link_to "EVENTS", events_path %></li>
            <li><%= link_to "ANNOUNCEMENTS", announcements_path, class: "active" %></li>

            <!-- <li><%= link_to "USERS", users_path %></li> -->
        </ul>
    </nav>
    
    <h1>New Announcement</h1>

    <ul id="toolbar">
        <li><%= link_to '+ Add', new_announcement_path, class: "active" %></li>
        <li><%= link_to 'Edit', announcements_path %></li>
    </ul>

    <%= render 'form', announcement: @announcement %>

</body>

app/views/announcements/show.html.erb
<!DOCTYPE html>
<head>
    <meta charset='utf-8'/>
    <title>Duke Rewards</title>
    <%= stylesheet_link_tag "application.css" %>
    <link href="https://fonts.googleapis.com/css?family=Merriweather:400,400i,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300;0,400;0,700;1,400&display=swap" rel="stylesheet">
</head>

<body>
  <p id="notice"><%= notice %></p>

  <nav>
    <ul id="menu">
      <%= image_tag("duke_wordmark_white.png", :alt => "Duke Wordmark") %>
      <li class="name"> Duke Rewards </li>
      <li><%= link_to "REWARDS", rewards_path %></li>
      <li><%= link_to "EVENTS", events_path%></li>
      <li><%= link_to "ANNOUNCEMENTS", announcements_path, class: "active" %></li>

      <!-- <li><%= link_to "USERS", users_path %></li> -->
    </ul>
  </nav>

  <h1>View Announcement</h1>

  <ul id="toolbar">
      <li><%= link_to '+ Add', new_announcement_path %></li>
      <li><%= link_to 'Edit', announcements_path, class: "active" %></li>
  </ul>

  <div class="edit">
    
    <%= link_to 'Return to All Announcements', announcements_path, class: "back" %>
    <%= link_to 'Edit', edit_announcement_path(@announcement), class: "back" %>
  
    <div class="view">
      <div class="showlabel">
        <label>Title:</label>
        <label class="autofilled"><%= @announcement.title %></label>
      </div>

      <div class="showlabel">
        <label>Description:</label>
        <label class="autofilled"><%= @announcement.description %></label>
      </div>

      <div class="showlabel">
        <label>Category:</label>
        <label class="autofilled"><%= @announcement.category %></label>
      </div>
    </div>
  </div>
</body>