config/routes.rb
Rails.application.routes.draw do
  root "events#index"
  get "/events/selectEvent" => "events#selectEvent" # if this line is after resources events, it will think selectEvent is an id
  get "/events/qrCode/:id" => "events#qrCode", as: "event_qrCode"
  get "/rewards/testEmail" => "rewards#testEmail"
  get "/rewards/:id/editRedemption" => "rewards#editRedemption", as: "edit_redemption"
  resources :users
  resources :announcements
  resources :rewards
  resources :events
  resources :redemptions
 
  get "/cheese" => "events#getAllEvents"
  get "/userFromToken" => "users#user_info"
  get "/userRewards" => "users#getRewards"
  patch "/usersMobile/:netid" => "users#updateFromMobile"
  patch "/usersMobile" => "users#updateFromMobile"
  patch "/redeem/:id" => "rewards#redeemReward"
  get "/users/showImage/:id" => "users#showImage", as: :user_showImage
  post "/attend/:id" => "users#eventScan"
  get "/confirmReward/:qrcode" => "rewards#confirmReward"
  get "/uniqueUsername" => "users#uniqueUsername"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  # Render Web App Interface

  # get "/events" => "events#index"
  # get "/rewards" => "rewards#index"
  # get "/announcements" => "announcements#index"
  # get "/users" => "users#index"

end

app/models/reward.rb
class Reward < ApplicationRecord
    validates :name, presence: true
    validates :description, presence: true
    validates :points, presence: true
    validates :category, presence: true
    validates :email, presence: true
    has_many :redemptions
    has_many :users, through: :redemptions
    has_one_attached :photo

    validates_presence_of :one_of_expiry_quantity_or_expiry_time, :message => "must not be blank"
    # validates_presence_of :name_, :message => "must not be blank"

  private
    # def name_
    #     return !name.blank?
    # end
    # remove validates :name to validates_presence_of to make the html of the fields not mess up when there is a validation error

    def one_of_expiry_quantity_or_expiry_time
        # puts location.blank?
        # puts expiry_quantity.blank?
        # puts "---------------"
        if expiry_time.blank? && expiry_quantity.blank?
            # errors.add(:base, "Specify a charge or a payment, not both")
            return false
        else
            return true
        end
    end

end

app/controllers/rewards_controller.rb
class RewardsController < ApplicationController
  before_action :set_reward, only: [:show, :edit, :update, :destroy]

  # GET /rewards
  # GET /rewards.json
  def index
    # @rewards = Reward.all
    @rewards = Reward.order('created_at DESC')
    @rewards.each do |reward|
      if reward.photo.attached?
        reward.image = url_for(reward.photo)
      end
    end
    # render json: {status: 'SUCCESS', message: 'Loaded rewards', data:@rewards}, status: :ok
    respond_to do |format|
        format.html 
        format.json { render json: {status: 'SUCCESS', message: 'Loaded rewards', data:@rewards}, status: :ok}
    end
  end

  # GET /rewards/1
  # GET /rewards/1.json
  def show
  end

  # GET /rewards/new
  def new
    @reward = Reward.new
  end

  # GET /rewards/1/edit
  def edit
  end

  # POST /rewards
  # POST /rewards.json
  def create
    @reward = Reward.new(reward_params)

    respond_to do |format|
      if @reward.save
        InfoMailer.with(reward: @reward).new_reward_email.deliver_later
        format.html { redirect_to @reward, notice: 'Reward was successfully created.' }
        format.json { render :show, status: :created, location: @reward }
      else
        format.html { render :new }
        format.json { render json: @reward.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rewards/1
  # PATCH/PUT /rewards/1.json
  def update
    respond_to do |format|
      if @reward.update(reward_params)
        format.html { redirect_to @reward, notice: 'Reward was successfully updated.' }
        format.json { render :show, status: :ok, location: @reward }
      else
        format.html { render :edit }
        format.json { render json: @reward.errors, status: :unprocessable_entity }
      end
    end    
  end

  def editRedemption
    puts params[:id]
    set_reward
  end

  # GET /rewards/testEmail
  def testEmail
    InfoMailer.with(reward: Reward.first, user: User.first).new_reward_email.deliver_later
  end

  # PATCH/PUT /redeem/1
  def redeemReward
    # get user and reward
    reward = Reward.find_by(id: params[:id])
    user = User.find_by(netid: params[:netid])
    if user == nil || reward == nil
      render json: {status: 'ERROR', message: 'Reward quantity not updated. User and/or Reward not found'}, status: :unprocessable_entity
      return
    end

    # user already redeemed this reward
    if user.rewards.include?(reward)
      render json: {status: 'REPEAT', message: 'User already redeemed reward'}
      return
    end

    
    if(reward.expiry_quantity < 1)
        render json: {status: 'ERROR', message: 'No Reward Left'}
        return
    else
        reward.expiry_quantity = reward.expiry_quantity - 1
        reward.save
    end

    # Xcode made the check for if the user had enough points but we'll check again
    # Ideally that is updated every time the user gains more points with a GET request
    if reward.category.downcase == "athletics"
      if reward.points > user.athletics_points
        render json: {status: 'ERROR', message: 'Insufficient athletic points'}
        return
      else
        user.athletics_points = user.athletics_points - reward.points
        user.save
      end
    elsif reward.category.downcase == "dining"
      if reward.points > user.dining_points
        render json: {status: 'ERROR', message: 'Insufficient dining points'}
        return
      else
        user.dining_points = user.dining_points - reward.points
        user.save
      end
    else
      render json: {status: 'ERROR', message: 'Reward category error'}
      return
    end

    # link user with reward
    user.rewards << reward

    # give QR code to this redemption model
    redemption = Redemption.find_by(user_id: user.id, reward_id: reward.id)
    redemption.QRcode = redemption.hash
    redemption.save

    # eventually do something with user email to reward email
    InfoMailer.with(reward: reward, user: user).new_reward_email.deliver_later

    # puts("----------------------------------------\n")
    # puts(user.dining_points)
    # puts(user.athletics_points)
    # puts("----------------------------------------\n")

    render json: {status: 'SUCCESS', message: 'Updated reward quantity and user points', data: user, reward: reward}, status: :ok
  end

  # GET /confirmReward/:qrcode
  def confirmReward
    # admin scans user reward to confirm their reward
    redemption = Redemption.find_by(QRcode: params[:qrcode])
    if redemption == nil
      render json: {status: 'FAILED'}
    else
      if redemption.dateHandled == nil
        user = User.find_by(id: redemption.user_id)
        reward = Reward.find_by(id: redemption.reward_id)
        redemption.adminNetID = params[:netid]
        redemption.dateHandled = DateTime.now
        redemption.save
        render json: {status: 'SUCCESS', data: {studentName: user.name, rewardName: reward.name}}
      else
        render json: {status: 'REPEAT'}
      end
    end
  end

  # DELETE /rewards/1
  # DELETE /rewards/1.json
  def destroy
    @reward.destroy
    respond_to do |format|
      format.html { redirect_to rewards_url, notice: 'Reward was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reward
      @reward = Reward.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def reward_params
      params.require(:reward).permit(:name, :start_time, :end_time, :location, :description, :points, :category, :expiry_time, :expiry_quantity, :email, :image, :photo)
      # this doesn't seem to affect what parameters gets through from a PATCH request
    end
end

app/helpers/rewards_helper.rb
module RewardsHelper
end

app/views/rewards/_form.html.erb
<%= form_with(model: reward, local: true) do |form| %>
  <% if reward.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(reward.errors.count, "error") %> prohibited this reward from being saved:</h2>

      <ul>
        <% reward.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name, "Reward Name:" %>
    <%= form.text_field :name, class: "short-text validationFixedWidth" %>
  </div>

  <div class="field">
    <%= form.label :category, "Category:" %>
    <%= form.select :category, ["Athletics","Dining"], {:prompt => "Select Category"}, class: "validationFixedWidthCategory" %>
  </div>

  <div class="field">
    <%= form.label :points, "Points:" %>
    <%= form.number_field :points, class: "number validationFixedWidth" %>
  </div>

  <div class="field">
    <%= form.label :start_time, "Start Time:" %>
    <%= form.datetime_select :start_time, { :order => [:day, :month, :year, :hour, :minute], :start_year => Time.now.year, :include_blank => true }, class: "time" %>
  </div>

  <div class="field">
    <%= form.label :end_time, "End Time:" %>
    <%= form.datetime_select :end_time, { :order => [:day, :month, :year, :hour, :minute], :start_year => Time.now.year, :include_blank => true }, class: "time" %>
  </div>

  <div class="field">
    <%= form.label :location, "Location:" %>
    <%= form.text_field :location, class: "short-text validationFixedWidth" %>
  </div>

  <div class="field">
    <%= form.label :description, "Description:" %>
    <%= form.text_area :description, class: "validationFixedWidthDescription" %>
  </div>

  <div class="field">
    <%= form.label :expiry_time, "Expiry Time:" %>
    <%= form.datetime_select :expiry_time, { :order => [:day, :month, :year, :hour, :minute], :start_year => Time.now.year, :include_blank => true }, class: "time" %>
  </div>

  <div class="field">
    <%= form.label :expiry_quantity, "Expiry Quantity:" %>
    <%= form.number_field :expiry_quantity, class: "number" %>
  </div>

  <div class="field">
    <%= form.label :email, "Contact Email:" %>
    <%= form.text_field :email, class: "short-text validationFixedWidth" %>
  </div>

  <div class="field">
    <%= form.label "Photo:" %>
    <%= form.file_field :photo, class: "file" %>
  </div>

  <div class="actions">
    <%= form.submit "Submit Reward", class: "submit" %>
  </div>
<% end %>

app/views/rewards/edit.html.erb
<!DOCTYPE html>
<head>
    <meta charset='utf-8'/>
    <title>Duke Rewards</title>
    <%= stylesheet_link_tag "application.css" %>
    <link href="https://fonts.googleapis.com/css?family=Merriweather:400,400i,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300;0,400;0,700;1,400&display=swap" rel="stylesheet">
</head>

<body>
    <nav>
        <ul id="menu">
            <%= image_tag("duke_wordmark_white.png", :alt => "Duke Wordmark") %>
            <li class="name"> Duke Rewards </li>
            <li><%= link_to "REWARDS", rewards_path, class: "active" %></li>
            <li><%= link_to "EVENTS", events_path %></li>
            <li><%= link_to "ANNOUNCEMENTS", announcements_path %></li>

            <!-- <li><%= link_to "USERS", users_path %></li> -->
        </ul>
    </nav>
    
    <h1>Editing Reward</h1>

    <ul id="toolbar">
        <li><%= link_to '+ Add', new_reward_path %></li>
        <li><%= link_to 'Edit', rewards_path, class: "active" %></li>
    </ul>
    
    <div class="edit">
        <%= link_to 'Return to All Rewards', rewards_path, class: "back" %>
        <%= link_to 'Show', @reward, class: "back" %>
        <%= render 'form', reward: @reward %>
    </div>
</body>

app/views/rewards/editRedemption.html.erb
<!DOCTYPE html>
<head>
    <meta charset='utf-8'/>
    <title>Duke Rewards</title>
    <%= stylesheet_link_tag "application.css" %>
    <link href="https://fonts.googleapis.com/css?family=Merriweather:400,400i,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300;0,400;0,700;1,400&display=swap" rel="stylesheet">
</head>

<body>
    <nav>
        <ul id="menu">
            <%= image_tag("duke_wordmark_white.png", :alt => "Duke Wordmark") %>
            <li class="name"> Duke Rewards </li>
            <li><%= link_to "REWARDS", rewards_path, class: "active" %></li>
            <li><%= link_to "EVENTS", events_path %></li>
            <li><%= link_to "ANNOUNCEMENTS", announcements_path %></li>

            <!-- <li><%= link_to "USERS", users_path %></li> -->
        </ul>
    </nav>
    
    <h1>Editing Reward Redemption</h1>

    
    
    <div class="edit">
        <%= link_to 'Return', @reward, class: "back" %>
    </div>

    <div>
        <% if @reward.users.empty? %>
            <label class="autofilled">Not Redeemed Yet!</label>
        <% else %>
        
           
            
            <%= render :partial => "redemptions/form", :locals => {:reward => @reward} %>
                
        
        <% end %>
      </div>
</body>

app/views/rewards/index.html.erb
<!DOCTYPE html>
<head>
    <meta charset='utf-8'/>
    <title>Duke Rewards</title>
    <%= stylesheet_link_tag "application.css" %>
    <link href="https://fonts.googleapis.com/css?family=Merriweather:400,400i,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300;0,400;0,700;1,400&display=swap" rel="stylesheet">
</head>

<body>
  <p id="notice"><%= notice %></p>

  <nav>
    <ul id="menu">
      <%= image_tag("duke_wordmark_white.png", :alt => "Duke Wordmark") %>
      <li class="name"> Duke Rewards </li>
      <li><%= link_to "REWARDS", rewards_path, class: "active" %></li>
      <li><%= link_to "EVENTS", events_path%></li>
      <li><%= link_to "ANNOUNCEMENTS", announcements_path %></li>

      <!-- <li><%= link_to "USERS", users_path %></li> -->
    </ul>
  </nav>

  <h1>Rewards</h1>

  <h2>Any reward that gets displayed in the Duke Rewards mobile app must be created here. When creating a new reward, it is mandatory to fill in the reward name, description, points amount, category, and contact email. For experiential rewards, you must fill in the start and end time, which refer to the time of the reward experience. To set the expiry of the reward, you must also fill in at least one of the options between expiry quantity and expiry time. The contact email provided will be notified whenever a student redeems this reward. Once they are notified, it is highly suggested for the contact person to reach out to users who redeem their reward for more specifics about the reward redemption process.</h2>

  <ul id="toolbar">
      <li><%= link_to '+ Add', new_reward_path %></li>
      <li><%= link_to 'Edit', rewards_path, class: "active" %></li>
  </ul>

  <div>
    <table>
      <thead>
        <tr>
          <th>Name</th>
          <th>Start Time</th>
          <th>End Time</th>
          <th>Location</th>
          <th>Description</th>
          <th>Points</th>
          <th>Category</th>
          <th>Expiry Time</th>
          <th>Expiry Quantity</th>
          <th>Action</th>
        </tr>
      </thead>

      <tbody>
        <% @rewards.each do |reward| %>
          <tr>
            <td><%= reward.name %></td>
            <% if reward.start_time == nil %>
              <td><%= reward.start_time %></td>
            <% else %>
              <td><%= reward.start_time.strftime("%F %H:%M %Z") %></td>
            <% end %>
            <% if reward.end_time == nil %>
              <td><%= reward.end_time %></td>
            <% else %>
              <td><%= reward.end_time.strftime("%F %H:%M %Z") %></td>
            <% end %>
            <td><%= reward.location %></td>
            <td><%= reward.description %></td>
            <td class="center"><%= reward.points %></td>
            <td class="center"><%= reward.category %></td>
            <% if reward.expiry_time == nil %>
              <td><%= reward.expiry_time %></td>
            <% else %>
              <td><%= reward.expiry_time.strftime("%F %H:%M %Z") %></td>
            <% end %>
            <td class="center"><%= reward.expiry_quantity %></td>
            <td class="no-wrap">
              <button><%= link_to 'Details', reward %></button><br>
              <button><%= link_to 'Edit', edit_reward_path(reward) %></button><br>
              <button><%= link_to 'Remove', reward, method: :delete, data: { confirm: 'Are you sure?' } %></button>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

</body>

app/views/rewards/new.html.erb
<!DOCTYPE html>
<head>
    <meta charset='utf-8'/>
    <title>Duke Rewards</title>
    <%= stylesheet_link_tag "application.css" %>
    <link href="https://fonts.googleapis.com/css?family=Merriweather:400,400i,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300;0,400;0,700;1,400&display=swap" rel="stylesheet">
</head>

<body>
    <nav>
        <ul id="menu">
            <%= image_tag("duke_wordmark_white.png", :alt => "Duke Wordmark") %>
            <li class="name"> Duke Rewards </li>
            <li><%= link_to "REWARDS", rewards_path, class: "active" %></li>
            <li><%= link_to "EVENTS", events_path %></li>
            <li><%= link_to "ANNOUNCEMENTS", announcements_path %></li>

            <!-- <li><%= link_to "USERS", users_path %></li> -->
        </ul>
    </nav>
    
    <h1>New Reward</h1>

    <ul id="toolbar">
        <li><%= link_to '+ Add', new_reward_path, class: "active" %></li>
        <li><%= link_to 'Edit', rewards_path %></li>
    </ul>
    
    <%= render 'form', reward: @reward %>

</body>

app/views/rewards/show.html.erb
<!DOCTYPE html>
<head>
    <meta charset='utf-8'/>
    <title>Duke Rewards</title>
    <%= stylesheet_link_tag "application.css" %>
    <link href="https://fonts.googleapis.com/css?family=Merriweather:400,400i,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300;0,400;0,700;1,400&display=swap" rel="stylesheet">
</head>

<body>
  <p id="notice"><%= notice %></p>

  <nav>
    <ul id="menu">
      <%= image_tag("duke_wordmark_white.png", :alt => "Duke Wordmark") %>
      <li class="name"> Duke Rewards </li>
      <li><%= link_to "REWARDS", rewards_path, class: "active" %></li>
      <li><%= link_to "EVENTS", events_path%></li>
      <li><%= link_to "ANNOUNCEMENTS", announcements_path %></li>

      <!-- <li><%= link_to "USERS", users_path %></li> -->
    </ul>
  </nav>

  <h1>View Reward</h1>

  <ul id="toolbar">
    <li><%= link_to '+ Add', new_reward_path %></li>
    <li><%= link_to 'Edit', rewards_path, class: "active" %></li>
  </ul>

  <div class="edit">
    <%= link_to 'Return to All Rewards', rewards_path, class: "back" %>
    <%= link_to 'Edit', edit_reward_path(@reward), class: "back" %>
    <!-- <%= link_to 'Edit redemption', edit_redemption_path(@reward), class: "back" %> -->

    <div class="view">
      <div class="showlabel">
        <label>Name:</label>
        <label class="autofilled"><%= @reward.name %></label>
      </div>
      
      <div class="showlabel">
        <label>Start time:</label>
        <% if @reward.start_time == nil %>
          <label class="autofilled"><%= @reward.start_time %></label>
        <% else %>
          <label class="autofilled"><%= @reward.start_time.strftime("%F %H:%M %Z") %></label>
        <% end %>
      </div>

      <div class="showlabel">
        <label>End time:</label>
        <% if @reward.end_time == nil %>
          <label class="autofilled"><%= @reward.end_time %></label>
        <% else %>
          <label class="autofilled"><%= @reward.end_time.strftime("%F %H:%M %Z") %></label>
        <% end %>
      </div>

      <div class="showlabel">
        <label>Location:</label>
        <label class="autofilled"><%= @reward.location %></label>
      </div>

      <div class="showlabel">
        <label>Description:</label>
        <label class="autofilled"><%= @reward.description %></label>
      </div>

      <div class="showlabel">
        <label>Points:</label>
        <label class="autofilled"><%= @reward.points %></label>
      </div>

      <div class="showlabel">
        <label>Category:</label>
        <label class="autofilled"><%= @reward.category %></label>
      </div>

      <div class="showlabel">
        <label>End time:</label>
        <% if @reward.expiry_time == nil %>
          <label class="autofilled"><%= @reward.expiry_time %></label>
        <% else %>
          <label class="autofilled"><%= @reward.expiry_time.strftime("%F %H:%M %Z") %></label>
        <% end %>
      </div>

      

      <div class="showlabel">
        <label>Expiry quantity:</label>
        <label class="autofilled"><%= @reward.expiry_quantity %></label>
      </div>

      <div class="showlabel">
        <label>Contact email:</label>
        <label class="autofilled"><%= @reward.email %></label>
      </div>

      <div class="showlabel">
        <label>Photo:</label>
        <% if @reward.photo.attached? %>
          <label class="autofilled"><image src="<%=(url_for(@reward.photo))%>" id="responsive-image"></label> 
        <% else %>
          <label class="autofilled">No photo available</label> 
        <% end %>
      </div>

      <div class="showlabel">
        <label>Redeemed By:</label>
        <% if @reward.users.empty? %>
          <label class="autofilled">Not Redeemed Yet!</label>
        <% else %>
          <div>
            <table>
              <thead>
                <tr>
                  <th>Student Email</th>
                  <th>Admin Initial</th>
                  <th>Date Handled</th>
                </tr>
              </thead>
      
              <tbody>
                <% @reward.users.each do |user| %>
                  <tr>
                    <td><%= user.email %></td>
                    <td><%= Redemption.find_by(user_id: user.id, reward_id: @reward.id).adminNetID %></td>
                    <td><%= Redemption.find_by(user_id: user.id, reward_id: @reward.id).dateHandled %></td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        <% end %>
      </div>

    </div>
  </div>
</body>