config/routes.rb
Rails.application.routes.draw do
  root "events#index"
  get "/events/selectEvent" => "events#selectEvent" # if this line is after resources events, it will think selectEvent is an id
  get "/events/qrCode/:id" => "events#qrCode", as: "event_qrCode"
  get "/rewards/testEmail" => "rewards#testEmail"
  get "/rewards/:id/editRedemption" => "rewards#editRedemption", as: "edit_redemption"
  resources :users
  resources :announcements
  resources :rewards
  resources :events
  resources :redemptions
 
  get "/cheese" => "events#getAllEvents"
  get "/userFromToken" => "users#user_info"
  get "/userRewards" => "users#getRewards"
  patch "/usersMobile/:netid" => "users#updateFromMobile"
  patch "/usersMobile" => "users#updateFromMobile"
  patch "/redeem/:id" => "rewards#redeemReward"
  get "/users/showImage/:id" => "users#showImage", as: :user_showImage
  post "/attend/:id" => "users#eventScan"
  get "/confirmReward/:qrcode" => "rewards#confirmReward"
  get "/uniqueUsername" => "users#uniqueUsername"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  # Render Web App Interface

  # get "/events" => "events#index"
  # get "/rewards" => "rewards#index"
  # get "/announcements" => "announcements#index"
  # get "/users" => "users#index"

end

app/models/event.rb
class Event < ApplicationRecord

    # validates :name, presence: true
    # validates :start_time, presence: true
    # validates :end_time, presence: true
    # # validates :time, presence: true
    # validates :location, presence: true
    # validates :description, presence: true
    validates :points, presence: true
    validates :radius, presence: true
    # validates :category, presence: true
    # # has_secure_token :QRnumber
    # # validates_uniqueness_of :QRnumber

    # no check for uniqueness of QRnumber - it is the Event model's hash

    has_many :attendances
    has_many :users, through: :attendances
    
    attribute :name 
    attribute :start_time
    attribute :end_time
    attribute :location
    attribute :description
    attribute :category
    attribute :image
    # validates :points, presence: true

    # attr_accessor :name, :start_time, :end_time, :location, :description, :category, :image
  
    # def as_json(options={})
    #   super(methods: [:name, :start_time, :end_time, :location, :description, :category, :image])
    #   # this allows the json rendered to show all the attributes, even ones not stored in active record
    # end
  end

app/controllers/events_controller.rb
require 'net/http'
require 'json'
require 'uri'

class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events/qrCode/:id
  def qrCode
    params.each do |k,v|
      puts "key: #{k} value: #{v}"
    end
    matchEvents
    @matchEvents.each do |e|
      if e.eventid == Event.find_by(id: params[:id]).eventid
        @event = e
      end
    end
  end

  # GET /events
  # GET /events.json
  def index 
    # Events are sorted based on how they were received from the calendar api currently (7/22/2020)
    matchEvents
    # this call should set @events to be all the events with points associated
    @events = @matchEvents

    # @events.each do |e|
    #   e.attributes.each do |k,v|
    #     puts "-------------------------------"
    #     puts k
    #     puts v
    #   end
    # end
    #@events = Event.order('start_time DESC')
    @matchEvents.each do |e| 
      if e.name.include?("MED")
        e.category = "Dining"
      else
        e.category = "Athletics"
      end
    end
    respond_to do |format|
       format.html 
       format.json { render json: {status: 'SUCCESS', message: 'Loaded events', data:@matchEvents}, status: :ok}
    end
  end
 

  #GET /cheese
  def getAllEvents()
    event_json = Eventsapi.getEventsData() 
    correct_events = Eventsapi.getEventsWithCategory(event_json, 'Health/Wellness')
    @events = Eventsapi.toEventModel(correct_events)

    #sports = ["baseball", "mbball", "wbball", "cross", "fencing", "fhockey", "football", "mgolf", "wgolf", "mlax", "wlax", "rowing", "msoc", "wsoc", "softball", "mten", "wten","tf", "vb"]
    sports = ["football"] # small sample
    sports.each do |s|
      athletics_events_json = Eventsapi.getAthleticsData(s)
      athletics_correct_events = Eventsapi.getAthleticsJson(athletics_events_json)
      @events = @events + Eventsapi.toEventModel(athletics_correct_events)
    end

    # event_json = Eventsapi.getEventsData() 
    # event_json1 = Eventsapi.getFootballData()
    # event_json2 = Eventsapi.getBaseballData()
    # event_json3 = Eventsapi.getMbballData()
    # event_json4 = Eventsapi.getWbballData()
    # event_json5 = Eventsapi.getCrossData()
    # event_json6 = Eventsapi.getFencingData()
    # event_json7 = Eventsapi.getFhockeyData()
    # event_json8 = Eventsapi.getMgolfData()
    # event_json9 = Eventsapi.getWgolfData()
    # event_json10 = Eventsapi.getMlaxData()
    # event_json11 = Eventsapi.getWlaxData()
    # event_json12 = Eventsapi.getRowingData()
    # event_json13 = Eventsapi.getMsocData()
    # event_json14 = Eventsapi.getWsocData()
    # event_json15 = Eventsapi.getSoftballData()
    # event_json16 = Eventsapi.getSwimData()
    # event_json17 = Eventsapi.getMtenData()
    # event_json18 = Eventsapi.getWtenData()
    # event_json19 = Eventsapi.getTfData()
    # event_json20 = Eventsapi.getVbData()

    
  
    # correct_events = Eventsapi.getEventsWithCategory(event_json, 'Health/Wellness')
    # correct_events1 = Eventsapi.getAthleticsJson(event_json1)
    # correct_events2 = Eventsapi.getAthleticsJson(event_json2)
    # correct_events3 = Eventsapi.getAthleticsJson(event_json3)
    # correct_events4 = Eventsapi.getAthleticsJson(event_json4)
    # correct_events5 = Eventsapi.getAthleticsJson(event_json5)
    # correct_events6 = Eventsapi.getAthleticsJson(event_json6)
    # correct_events7 = Eventsapi.getAthleticsJson(event_json7)
    # correct_events8 = Eventsapi.getAthleticsJson(event_json8)
    # correct_events9 = Eventsapi.getAthleticsJson(event_json9)
    # correct_events10 = Eventsapi.getAthleticsJson(event_json10)
    # correct_events11 = Eventsapi.getAthleticsJson(event_json11)
    # correct_events12 = Eventsapi.getAthleticsJson(event_json12)
    # correct_events13 = Eventsapi.getAthleticsJson(event_json13)
    # correct_events14 = Eventsapi.getAthleticsJson(event_json14)
    # correct_events15 = Eventsapi.getAthleticsJson(event_json15)
    # correct_events16 = Eventsapi.getAthleticsJson(event_json16)
    # correct_events17 = Eventsapi.getAthleticsJson(event_json17)
    # correct_events18 = Eventsapi.getAthleticsJson(event_json18)
    # correct_events19 = Eventsapi.getAthleticsJson(event_json19)
    # correct_events20 = Eventsapi.getAthleticsJson(event_json20)


    #@events = Eventsapi.toEventModel(correct_events)  + Eventsapi.toEventModel(correct_events1) + Eventsapi.toEventModel(correct_events2) + Eventsapi.toEventModel(correct_events3) + Eventsapi.toEventModel(correct_events4) + Eventsapi.toEventModel(correct_events5) + Eventsapi.toEventModel(correct_events6) + Eventsapi.toEventModel(correct_events7) + Eventsapi.toEventModel(correct_events8) + Eventsapi.toEventModel(correct_events9) + Eventsapi.toEventModel(correct_events10) + Eventsapi.toEventModel(correct_events11) + Eventsapi.toEventModel(correct_events12) + Eventsapi.toEventModel(correct_events13) + Eventsapi.toEventModel(correct_events14) + Eventsapi.toEventModel(correct_events15) + Eventsapi.toEventModel(correct_events16) + Eventsapi.toEventModel(correct_events17) + Eventsapi.toEventModel(correct_events18) + Eventsapi.toEventModel(correct_events19) + Eventsapi.toEventModel(correct_events20)
    
    
    # render json: @events, status: :ok
    # don't render here because the method calling getAllEvents will render
  end 


  # GET /events/1
  # GET /events/1.json
  def show
    matchEvents
    @matchEvents.each do |e|
      if e.eventid == Event.find_by(id: params[:id]).eventid
        @event = e
      end
    end
  end


  # GET /events/new
  def new
    # called when user presses add for an event
    getAllEvents
    matchEvents
    @event = Event.new 
    # this @event is used to check if there are any errors right now

    @selected = false
    # Event.where(QRnumber: "TEMP").destroy_all
  end

  def generateMap
    # map selected event to eventid
    getAllEvents
    @map = Hash.new("ERROR")
    @events.each do |c|
      @map["#{Time.strptime(c.start_time, "%Y-%m-%dT%H:%M:%S%z").in_time_zone.strftime("%F %H:%M %Z")}  #{c.name}"] = c.eventid
    end
  end

  # GET /events/selectEvent
  def selectEvent
    generateMap

    # puts "-------------------------------"
    # puts "selectEvent"
    # puts params[:selected]
    # puts @map[params[:selected]]
    # puts "-------------------------------"
    
    if params[:selected] != "Select Event" && params[:selected] != "ERROR"
      @selected = true
      @events.each do |e|
        if e.eventid == @map[params[:selected]]
          @event = e
          break
        end
      end
      session[:selectedEvent] = @event.eventid
      render "new"
    else
      matchEvents
      render :controller => 'events', :action => 'new'
    end


    # <div class="field">
    #   <% event.attributes.each do |k,v| %>
    #     <%= form.hidden_field k, { :value => v }%>
    #   <% end %>
    # </div>
  end

  # GET /events/1/edit
  def edit
    matchEvents
    @matchEvents.each do |e|
      if e.eventid == Event.find_by(id: params[:id]).eventid
        @event = e
      end
    end
  end

  # POST /events
  # POST /events.json
  def create
    # when submit is clicked on new tab
    # @event = Event.new(event_params)
    getAllEvents
    sessionEventID = session[:selectedEvent]
    webEvent = nil
    @events.each do |e|
      # puts e.eventid
      # puts tempEvent.eventid
      if e.eventid == sessionEventID
        webEvent = e
        break
      end
    end

    # params.each do |k,v|
    #   puts "-------------------------------"
    #   puts "key: #{k} value: #{v}"
    #   puts "-------------------------------"
    # end

    # webEvent.attributes.each do |k,v|
    #   puts "-------------------------------"
    #   puts "key: #{k} value: #{v}"
    #   puts "-------------------------------"
    # end
    
    @event = Event.new(eventid: sessionEventID, points: params[:event]["points"], radius: params[:event]["radius"])
    @event.QRnumber = @event.hash
    @event.name = webEvent.name
    @event.start_time = webEvent.start_time
    @event.end_time = webEvent.end_time
    @event.location = webEvent.location
    @event.description = webEvent.description
    @event.category = webEvent.category
    @event.image = webEvent.image
    @event.duration = ((webEvent.end_time.to_datetime - webEvent.start_time.to_datetime)*24 * 60).to_i
    if @event.save
      render "show"
    else
      matchEvents
      @selected = true
      render "new"
      #render json: {errors: @event.errors}, status: :unprocessable_entity
    end

    # respond_to do |format|
    #   if @event.save
    #     # format.html { redirect_to @event, notice: 'Event was successfully created.' }
    #     # format.json { render :show, status: :created, location: @event }
    #   else
    #     format.html { render :new }
    #     format.json { render json: @event.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def matchEvents
    getAllEvents
    @matchEvents = [] # events that exist in our database (points attached)
    @oppositeEvents = [] # events that do not exist in our database
    @events.each do |e|
      if e.start_time > Time.now
        if Event.exists?(eventid: e.eventid)
          @matchEvents << e
        else
          @oppositeEvents << e
        end
      end
    end
  end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_add_form.html.erb
<%= form_with(model: event, local: true) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
        <% event.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  

  <div class="field">
    <%= form.label :points, "Points:" %>
    <%= form.number_field :points, class: "number validationFixedWidth" %>
  </div>

  <div class="showlabel">
    <%= form.label :name, "Event Name:" %>
    <%= form.label :name, event.name, class: "autofilled" %>
  </div>

  <div class="showlabel">
    <%= form.label :category, "Category:" %>
    <%= form.label :category, event.category, class: "autofilled" %>
  </div>

  <div class="showlabel">
    <%= form.label :location, "Location:" %>
    <%= form.label :location, event.location, class: "autofilled" %>
  </div>

  <div class="showlabel field">
    <%= form.label :radius, "Event size:" %>
    <%= form.select :radius, ["None", "Small (< 20m)","Medium (20m - 100m)", "Large (100m - 300m)"], {:prompt => "Select radius."}, class: "validationFixedWidthRadius" %>
  </div>


  <div class="showlabel">
    <%= form.label :description, "Description:" %>
    <%= form.label :description, event.description, class: "autofilled" %>
  </div>

  <div class="showlabel">
    <%= form.label :start_time, "Start Time:" %>
    <%= form.label :start_time, event.start_time, class: "autofilled" %>
  </div>

  <div class="showlabel">
    <%= form.label :end_time, "End Time:" %>
    <%= form.label :end_time, event.end_time, class: "autofilled" %>
  </div>

  <div class="actions">
    <%= form.submit "Submit Event", class: "submit" %>
  </div>
<% end %>

app/views/events/_edit_form.html.erb
<%= form_with(model: event, local: true) do |form| %>
    <% if event.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>
  
        <ul>
          <% event.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  

  <div class="field">
    <%= form.label :points, "Points:" %>
    <%= form.number_field :points, class: "number" %>
  </div>
  <div class="field">
    <%= form.label :radius, "Event size:" %>
    <%= form.select :radius, ["None", "Small (< 20m)","Medium (20m - 100m)", "Large (100m - 300m)"], {:prompt => "Select radius."}, class: "validationFixedWidthRadius" %>
  </div>

  <div class="view">
      <div class="showlabel">
        <label>Name:</label>
        <label class="autofilled"><%= @event.name %></label>
      </div>

      <div class="showlabel">
        <label>Start time:</label>
        <label class="autofilled"><%= @event.start_time %></label>
      </div>

      <div class="showlabel">
        <label>End time:</label>
        <label class="autofilled"><%= @event.end_time %></label>
      </div>

      <div class="showlabel">
        <label>Location:</label>
        <label class="autofilled"><%= @event.location %></label>
      </div>

      <div class="showlabel">
        <label>Description:</label>
        <label class="autofilled"><%= @event.description %></label>
      </div>

      <div class="showlabel">
        <label>Points:</label>
        <label class="autofilled"><%= @event.points %></label>
      </div>

      <div class="showlabel">
        <label>Category:</label>
        <label class="autofilled"><%= @event.category %></label>
      </div>

      <div class="showlabel">
        <label>QR Code:</label>
        <%= RQRCode::QRCode.new(@event.QRnumber).as_svg( offset: 0, color: "000", shape_rendering: 'crispEdges', module_size: 6, standalone: true ).html_safe %>
      </div>
    
      <div class="actions">
        <%= form.submit "Submit Event", class: "submit" %>
      </div>
      </div>

  
<% end %>

app/views/events/_form.html.erb
<%= form_with(model: event, local: true) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
        <% event.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

 
  <div class="field">
    <%= form.label :name, "Event Name:" %>
    <%= form.label :name, event.name %>
    <!-- <%= form.select :name, @events.collect {|c| [ c.name ] }, {:prompt => "Select Event"} %>  -->
  </div>

  <!--
  <div class="field">
    <%= form.label :category, "Category:" %>
    <%= form.select :category, ["Athletics","Dining"], {:prompt => "Select Category"} %>
  </div>
  -->

  <div class="field">
    <%= form.label :points, "Points:" %>
    <%= form.number_field :points, class: "number" %>
  </div>

  <!--
  <div class="field">
    <%= form.label :start_time, "Start Time:" %>
    <%= form.datetime_select :start_time, { :order => [:day, :month, :year, :hour, :minute], :start_year => Time.now.year }, class: "time" %>
  </div>

  <div class="field">
    <%= form.label :end_time, "End Time:" %>
    <%= form.datetime_select :end_time, { :order => [:day, :month, :year, :hour, :minute], :start_year => Time.now.year }, class: "time" %>
  </div>

  <div class="field">
    <%= form.label :location, "Location:" %>
    <%= form.text_field :location, class: "short-text" %>
  </div>

  <div class="field">
    <%= form.label :radius, "Event size:" %>
    <%= form.select :radius, ["None", "Small (< 20m)","Medium (20m - 100m)", "Large (100m - 300m)"], {:prompt => "Select radius."}, class: "validationFixedWidthRadius" %>
  </div>

  <div class="field">
    <%= form.label :description, "Description:" %>
    <%= form.text_area :description%>
  </div>
   -->

  <div class="actions">
    <%= form.submit "Submit Event", class: "submit" %>
  </div>
<% end %>

app/views/events/_select_event_form.html.erb
<%= form_with(url: events_selectEvent_path, method: "get", local: true) do %>
    <div class="field">
    <% options = ["Select Event"] %>
    
    <% @oppositeEvents = @oppositeEvents.sort_by(&:start_time)%>
    <% @oppositeEvents.each do |c| %>
      
            
            <%options << "#{Time.strptime(c.start_time, "%Y-%m-%dT%H:%M:%S%z").in_time_zone.strftime("%F %H:%M %Z")}  #{c.name}" %>
            
           
    <% end %>
        <%= select_tag(:selected, options_for_select(options), :class => "select") %>
    </div>

    <div class="actions">
        <%= submit_tag("Select Event", :class => "button") %>
    </div>
<% end %>

app/views/events/edit.html.erb
<!DOCTYPE html>
<head>
    <meta charset='utf-8'/>
    <title>Duke Rewards</title>
    <%= stylesheet_link_tag "application.css" %>
    <link href="https://fonts.googleapis.com/css?family=Merriweather:400,400i,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300;0,400;0,700;1,400&display=swap" rel="stylesheet">
</head>

<body>
    <nav>
        <ul id="menu">
            <%= image_tag("duke_wordmark_white.png", :alt => "Duke Wordmark") %>
            <li class="name"> Duke Rewards </li>
            <li><%= link_to "REWARDS", rewards_path %></li>
            <li><%= link_to "EVENTS", events_path, class: "active" %></li>
            <li><%= link_to "ANNOUNCEMENTS", announcements_path %></li>

            <!-- <li><%= link_to "USERS", users_path %></li> -->
        </ul>
    </nav>

    <h1>Editing Event</h1>

    <ul id="toolbar">
        <li><%= link_to '+ Add', new_event_path %></li>
        <li><%= link_to 'Display', events_path, class: "active" %></li>
    </ul>
    
    <div class="edit">
        <%= link_to 'Return to All Events', events_path, class: "back" %>
        <%= link_to 'Show', @event, class: "back" %>
    <%= render 'edit_form', event: @event %>
    </div>
</body>

app/views/events/index.html.erb
<!DOCTYPE html>
<head>
    <meta charset='utf-8'/>
    <title>Duke Rewards</title>
    <%= stylesheet_link_tag "application.css" %>
    <link href="https://fonts.googleapis.com/css?family=Merriweather:400,400i,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300;0,400;0,700;1,400&display=swap" rel="stylesheet">
</head>

<body>
  <p id="notice"><%= notice %></p>

  <nav>
    <ul id="menu">
      <%= image_tag("duke_wordmark_white.png", :alt => "Duke Wordmark") %>
      <li class="name"> Duke Rewards </li>
      <li><%= link_to "REWARDS", rewards_path %></li>
      <li><%= link_to "EVENTS", events_path, class: "active" %></li>
      <li><%= link_to "ANNOUNCEMENTS", announcements_path %></li>

      <!-- <li><%= link_to "USERS", users_path %></li> -->
    </ul>
  </nav>

  <h1>Events</h1>

  <h2>Events are pulled from other sources. Select the event you wish to add to our rewards app in the "+ Add" tab. Then, fill in the corresponding points and select the event parameter to set up location tracking. An event parameter of “None” will not track how long students stay at events - only a QR code scan will confirm their attendance. Upon submitting the points and event parameter, a QR code will be generated. You can always refer back to the code by clicking “Show” in the table display of all events. </h2>

  <ul id="toolbar">
      <li><%= link_to '+ Add', new_event_path %></li>
      <li><%= link_to 'Display', events_path, class: "active" %></li>
  </ul>

  <div>
    <table>
      <thead>
        <tr>
          <th>Name</th>
          <th>Start Time</th>
          <th>End Time</th>
          <th>Location</th>
          <th>Radius</th>
          <th>Points</th>
          <th>Category</th>
          <th>Action</th>
        </tr>
      </thead>

      <tbody>
        <% @events.each do |event| %>
            <tr>
              <td><%= event.name %></td>
              <td><%= event.start_time.in_time_zone(ActiveSupport::TimeZone.new("Eastern Time (US & Canada)")).strftime("%F %H:%M %Z") %></td>
              <td><%= event.end_time.in_time_zone(ActiveSupport::TimeZone.new("Eastern Time (US & Canada)")).strftime("%F %H:%M %Z") %></td>
              <td><%= event.location %></td>
              <td><%= event.radius %></td>
              <td class="center"><%= event.points %></td>
              <td class="center"><%= event.category %></td>
              <td class="no-wrap">
                <button><%= link_to 'QR', event_qrCode_path(event.id) %></button><br>
                <button><%= link_to 'Details', event %></button><br>
                <button><%= link_to 'Edit', edit_event_path(event) %></button><br>
                <button><%= link_to 'Remove', event, method: :delete, data: { confirm: 'Are you sure?' } %></button>
              </td>
            </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</body>

app/views/events/new.html.erb
<!DOCTYPE html>
<head>
    <meta charset='utf-8'/>
    <title>Duke Rewards</title>
    <%= stylesheet_link_tag "application.css" %>
    <link href="https://fonts.googleapis.com/css?family=Merriweather:400,400i,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300;0,400;0,700;1,400&display=swap" rel="stylesheet">
</head>

<body>
    <nav>
        <ul id="menu">
            <%= image_tag("duke_wordmark_white.png", :alt => "Duke Wordmark") %>
            <li class="name"> Duke Rewards </li>
            <li><%= link_to "REWARDS", rewards_path %></li>
            <li><%= link_to "EVENTS", events_path, class: "active" %></li>
            <li><%= link_to "ANNOUNCEMENTS", announcements_path %></li>

            <!-- <li><%= link_to "USERS", users_path %></li> -->
        </ul>
    </nav>

    <h1>Load Event</h1>

    <ul id="toolbar">
        <li><%= link_to '+ Add', new_event_path, class: "active" %></li>
        <li><%= link_to 'Display', events_path %></li>
    </ul>

    <% if @selected %>
        <%= render 'add_form', event: @event%>
    <% else %>
        <%= render 'select_event_form', event: @event %>
    <% end %>

</body>

app/views/events/qrCode.html.erb
<h3 style="text-align:center"><%= @event.name %></h3>
<h3 style="text-align:center"><%= @event.start_time %></h3>

<%= link_to 'Back', events_path, class: "back" %>

<h4 style="text-align:center">
    <a href=<%= "https://chart.googleapis.com/chart?chs=545x545&cht=qr&chl=#{@event.QRnumber}&choe=UTF-8" %> target="_blank">The link to the same QR code shown below</a>
</h4>

<image src=<%="https://chart.googleapis.com/chart?chs=545x545&cht=qr&chl=#{@event.QRnumber}&choe=UTF-8"%> alt="QR code" class="imageCenter">

app/views/events/show.html.erb
<!DOCTYPE html>
<head>
    <meta charset='utf-8'/>
    <title>Duke Rewards</title>
    <%= stylesheet_link_tag "application.css" %>
    <link href="https://fonts.googleapis.com/css?family=Merriweather:400,400i,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300;0,400;0,700;1,400&display=swap" rel="stylesheet">
</head>

<body>
  <p id="notice"><%= notice %></p>

  <nav>
    <ul id="menu">
      <%= image_tag("duke_wordmark_white.png", :alt => "Duke Wordmark") %>
      <li class="name"> Duke Rewards </li>
      <li><%= link_to "REWARDS", rewards_path %></li>
      <li><%= link_to "EVENTS", events_path, class: "active" %></li>
      <li><%= link_to "ANNOUNCEMENTS", announcements_path %></li>

      <!-- <li><%= link_to "USERS", users_path %></li> -->
    </ul>
  </nav>

  <h1>View Event</h1>

  <ul id="toolbar">
      <li><%= link_to '+ Add', new_event_path %></li>
      <li><%= link_to 'Display', events_path, class: "active" %></li>
  </ul>

  <div class="edit">

    <%= link_to 'Return to All Events', events_path, class: "back" %>
    <%= link_to 'Edit', edit_event_path(@event), class: "back" %>

    <div class="view">
      <div class="showlabel">
        <label>Name:</label>
        <label class="autofilled"><%= @event.name %></label>
      </div>

      <div class="showlabel">
        <label>Start time:</label>
        <label class="autofilled"><%= @event.start_time %></label>
      </div>

      <div class="showlabel">
        <label>End time:</label>
        <label class="autofilled"><%= @event.end_time %></label>
      </div>

      <div class="showlabel">
        <label>Location:</label>
        <label class="autofilled"><%= @event.location %></label>
      </div>

      <div class="showlabel">
        <label>Event parameter:</label>
        <label class="autofilled"><%= @event.radius %></label>
      </div>

      <div class="showlabel">
        <label>Description:</label>
        <label class="autofilled"><%= @event.description %></label>
      </div>

      <div class="showlabel">
        <label>Points:</label>
        <label class="autofilled"><%= @event.points %></label>
      </div>

      <div class="showlabel">
        <label>Category:</label>
        <label class="autofilled"><%= @event.category %></label>
      </div>

      <div class="showlabel">
        <label>QR Code:</label>
        <%= RQRCode::QRCode.new(@event.QRnumber).as_svg( offset: 0, color: "000", shape_rendering: 'crispEdges', module_size: 6, standalone: true ).html_safe %>
      </div>

    </div>
  </div>
</body>